# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'ordering': ['?']},
        ),
    ]
